### ISSUE TITLE
Implement double view chart in figure 1 and 2

### ISSUE THREAD

**Issue by RainismZ** [RainismZ/data-visualization-project#7]
Encode zoomable L.A. map
Add project points to map
Add link and interaction between map and information view

**Comment by curran** [comment]
What is figure 1 and 2 referencing to? This issue is not a complete specification. Perhaps include images here as well?

Also the issue can be split up into subtasks, the scope seems too large here to be a single issue.

**Comment by seschultz** [comment]
I'm not sure what you mean by "double view chart"
